# Generated by Django 2.2 on 2020-08-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('granted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wish_app.Wish')),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='login_app.User')),
            ],
        ),
    ]
